GET http://localhost:3001/todos

###

POST http://localhost:3001/todo/new
Content-Type: application/json

{
    "text": "Get Lolipop",
    "complete": false
}

###

DELETE http://localhost:3001/todo/delete/64022f25ce459cb5d5cb73ef


###

PUT http://localhost:3001/todo/complete/64022e3ca3a81e6a6e0ab9e2